import { useEffect, useState } from 'react';
import { api, type ProductDetail, type ProductSummary } from '../../api';
function value(item: unknown): string { if (Array.isArray(item)) return item.join(', ') || '—'; if (typeof item === 'object' && item !== null) return JSON.stringify(item); return String(item || '—'); }
export function ProductGraph({ taskId }: { taskId: string }) {
  const [products, setProducts] = useState<ProductSummary[]>([]); const [selected, setSelected] = useState<ProductDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void (async () => { try { setLoading(true); const result = await api.products(taskId); setProducts(result.items); setSelected(result.items[0] ? await api.product(result.items[0].id) : null); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setLoading(false); } })(); }, [taskId]);
  async function select(product: ProductSummary) { try { setError(''); setSelected(await api.product(product.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  if (loading) return <p className="muted">Loading canonical products…</p>;
  if (error) return <p className="error">Unable to load the product graph: {error}</p>;
  if (!products.length) return <div className="empty-state"><h3>No canonical products yet</h3><p>Run the catalog workflow after uploading source files to build the Product and SKU graph.</p></div>;
  const product = selected?.data;
  return <div className="product-graph"><nav className="product-list" aria-label="Canonical products">{products.map((item) => <button key={item.id} className={selected?.id === item.id ? 'selected' : ''} onClick={() => void select(item)}><strong>{item.title}</strong><span>{item.external_id} · v{item.version}</span></button>)}</nav>{selected && product && <section className="product-detail"><div className="card-heading"><div><span className="kicker">CANONICAL PRODUCT</span><h3>{product.title}</h3></div><span className={`status ${product.status}`}>{product.status}</span></div><div className="fact-grid">{[['Product ID', product.external_id], ['Category', product.category], ['Garment type', product.garment_type], ['Material', product.materials], ['Fiber content', product.fiber_content], ['Origin', product.country_of_origin], ['Care', product.care_instructions], ['Manufacturer', product.manufacturer]].map(([label, item]) => <div key={String(label)}><span>{label}</span><strong>{value(item)}</strong></div>)}</div><h4>SKUs ({product.skus.length})</h4><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Color</th><th>Size</th><th>Price</th><th>Inventory</th></tr></thead><tbody>{product.skus.map((sku) => <tr key={sku.id}><td>{sku.external_id}</td><td>{sku.color || '—'}</td><td>{sku.size || '—'}</td><td>{sku.price || '—'}</td><td>{sku.inventory ?? '—'}</td></tr>)}</tbody></table></div><h4>Source evidence</h4><div className="evidence-list">{product.facts.map((fact) => <article key={fact.id}><strong>{fact.field_name}: {value(fact.value)}</strong><span>{fact.evidence.file_name} · {fact.evidence.location}</span><p>{fact.evidence.text || 'No excerpt captured.'}</p></article>)}{!product.facts.length && <p className="muted">No evidence records were captured for this product.</p>}</div><p className="graph-summary">Graph: {selected.graph.nodes.length} nodes · {selected.graph.edges.length} relationships</p></section>}</div>;
}
