import { useEffect, useState } from 'react';
import { api, type ProductDetail, type ProductSummary } from '../../api';
function value(item: unknown): string { if (Array.isArray(item)) return item.join(', ') || '—'; if (typeof item === 'object' && item !== null) return JSON.stringify(item); return String(item || '—'); }
export function ProductGraph({ projectId }: { projectId: string }) {
  const [products, setProducts] = useState<ProductSummary[]>([]); const [selected, setSelected] = useState<ProductDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void (async () => { try { setLoading(true); const result = await api.projectProducts(projectId); setProducts(result.items); setSelected(result.items[0] ? await api.product(result.items[0].id) : null); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setLoading(false); } })(); }, [projectId]);
  async function select(product: ProductSummary) { try { setError(''); setSelected(await api.product(product.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  if (loading) return <p className="muted">正在加载规范商品…</p>;
  if (error) return <p className="error">无法加载商品图谱：{error}</p>;
  if (!products.length) return <div className="empty-state"><h3>暂无规范商品</h3><p>上传源文件并运行商品目录工作流后，系统将在此构建 Product/SKU 图谱。</p></div>;
  const product = selected?.data;
  return <div className="product-graph"><nav className="product-list" aria-label="规范商品">{products.map((item) => <button key={item.id} className={selected?.id === item.id ? 'selected' : ''} onClick={() => void select(item)}><strong>{item.title}</strong><span>{item.external_id} · v{item.version}</span></button>)}</nav>{selected && product && <section className="product-detail"><div className="card-heading"><div><span className="kicker">规范商品</span><h3>{product.title}</h3></div><span className={`status ${product.status}`}>{product.status === 'confirmed' ? '已确认' : product.status}</span></div><div className="fact-grid">{[['商品 ID', product.external_id], ['商品分类', product.category], ['服装类型', product.garment_type], ['材质', product.materials], ['纤维成分', product.fiber_content], ['原产地', product.country_of_origin], ['护理说明', product.care_instructions], ['制造商', product.manufacturer]].map(([label, item]) => <div key={String(label)}><span>{label}</span><strong>{value(item)}</strong></div>)}</div><h4>SKU（{product.skus.length}）</h4><div className="table-wrap"><table><thead><tr><th>SKU</th><th>颜色</th><th>尺码</th><th>价格</th><th>库存</th></tr></thead><tbody>{product.skus.map((sku) => <tr key={sku.id}><td>{sku.external_id}</td><td>{sku.color || '—'}</td><td>{sku.size || '—'}</td><td>{sku.price || '—'}</td><td>{sku.inventory ?? '—'}</td></tr>)}</tbody></table></div><h4>来源证据</h4><div className="evidence-list">{product.facts.map((fact) => <article key={fact.id}><strong>{fact.field_name}: {value(fact.value)}</strong><span>{fact.evidence.file_name} · {fact.evidence.location}</span><p>{fact.evidence.text || '未记录原文片段。'}</p></article>)}{!product.facts.length && <p className="muted">该商品尚未记录来源证据。</p>}</div><p className="graph-summary">图谱：{selected.graph.nodes.length} 个节点 · {selected.graph.edges.length} 条关系</p></section>}</div>;
}
